name: Basic Pitch
_target_: pipeline.models.BasicPitchWrapper

weight_path: models/basic_pitch/assets/basic_pitch_pytorch_icassp_2022.pth

target_shape: b t f
complex: false

# Model specifics
sr: 22050
fft_hop: 256
n_overlapping_frames: 30
n_frames_chunk: 172
bins_per_semitone: 3

# Inference settings
inference_settings:
  onset_thresh: 0.5
  frame_thresh: 0.3
  min_note_len: 11
  min_freq: null
  max_freq: null
  multiple_pitch_bends: false
  melodia_trick: true
  midi_tempo: 120