name: pi_mir

channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.9
  - pytorch
  - torchaudio
  - pytorch-cuda=11.8
  - scipy=1.12
  - pip

  - pip:
      - pretty_midi
      - mir_eval
      - librosa
      - resampy
      - nnaudio
      - hydra-core
      - pandas
      - omegaconf
      - tqdm
      - matplotlib