defaults:
  - model: basic_pitch
  - dataset: maps
  - permutation: no_permutation
  - _self_

  - override hydra/job_logging: custom

evalutation:
  subsample_every: 64

hydra:
  sweeper:
    params:
      permutation: high_freq, random, no_permutation, microtonal
      dataset: maps, maestro