defaults:
  - model: basic_pitch
  - dataset: maps
  - permutation: no_permutation
  - _self_

  - override hydra/job_logging: custom

adapter:
  _target_: pipeline.permutations.InputAdapter

evalutation:
  subsample_every: 500

chunked_inference: True

hydra:
  sweeper:
    params:
      model: basic_pitch, timbre_trap
      permutation: high_freq, random, no_permutation, microtonal, fund_mask, harm_mask, soft_fund_mask, soft_harm_mask
      dataset: maps, maestro